--[[
	WARNING: Heads up! This script has not been verified by ScriptBlox. Use at your own risk!
]]
local allowedPartNames = {
"Common","InvertedCommon","ChromaticCommon","Uncommon","InvertedUncommon","ChromaticUncommon","Rare","InvertedRare","ChromaticRare","Epic","InvertedEpic","ChromaticEpic","Bit","InvertedBit","ChromaticBit","Icy","InvertedIcy","ChromaticIcy","Magma","InvertedMagma","ChromaticMagma","Dusk","InvertedDusk","ChromaticDusk","Pure","InvertedPure","ChromaticPure","Aqua","InvertedAqua","ChromaticAqua","Life","InvertedLife","ChromaticLife","Shine","InvertedShine","ChromaticShine","Legendary","InvertedLegendary","ChromaticLegendary","Mythical","InvertedMythical","ChromaticMythical","Godly","InvertedGodly","ChromaticGodly","Binary","InvertedBinary","ChromaticBinary","Frost","InvertedFrost","ChromaticFrost","Flare","InvertedFlare","ChromaticFlare","Arcane","InvertedArcane","ChromaticArcane","Runic","InvertedRunic","ChromaticRunic","Ascendant","InvertedAscendant","ChromaticAscendant","Stellar","InvertedStellar","ChromaticStellar","Aquavortex","InvertedAquavortex","ChromaticAquavortex","Pyro","InvertedPyro","ChromaticPyro","Nebula","InvertedNebula","ChromaticNebula","Paragon","InvertedParagon","ChromaticParagon","Immortal","InvertedImmortal","ChromaticImmortal","Ethereal","InvertedEthereal","ChromaticEthereal","Blaze","InvertedBlaze","ChromaticBlaze","Astral","InvertedAstral","ChromaticAstral","Odyssey","InvertedOdyssey","ChromaticOdyssey","Glacier","InvertedGlacier","ChromaticGlacier","Lunar","InvertedLunar","ChromaticLunar","Glisten","InvertedGlisten","ChromaticGlisten","Inverted Flare","InvertedInverted Flare","ChromaticInverted Flare","Divine","InvertedDivine","ChromaticDivine","Leviathan","InvertedLeviathan","ChromaticLeviathan","Omnipotent","InvertedOmnipotent","ChromaticOmnipotent","Eruption","InvertedEruption","ChromaticEruption","Blizzard","InvertedBlizzard","ChromaticBlizzard","Temporal","InvertedTemporal","ChromaticTemporal","Desolation","InvertedDesolation","ChromaticDesolation","Empyrean","InvertedEmpyrean","ChromaticEmpyrean","Aurora","InvertedAurora","ChromaticAurora","Abyssal","InvertedAbyssal","ChromaticAbyssal","Demonic","InvertedDemonic","ChromaticDemonic","Frostbite","InvertedFrostbite","ChromaticFrostbite","Purity","InvertedPurity","ChromaticPurity","Seraphin","InvertedSeraphin","ChromaticSeraphin","Guardian","InvertedGuardian","ChromaticGuardian","Vaporwave","InvertedVaporwave","ChromaticVaporwave","Cosmic","InvertedCosmic","ChromaticCosmic","Chronos","InvertedChronos","ChromaticChronos","Nuetron","InvertedNuetron","ChromaticNuetron","Beyond","InvertedBeyond","ChromaticBeyond","Depth","InvertedDepth","ChromaticDepth","Destiny","InvertedDestiny","ChromaticDestiny","Hypergiant","InvertedHypergiant","ChromaticHypergiant","Blossom","InvertedBlossom","ChromaticBlossom","Prismatic","InvertedPrismatic","ChromaticPrismatic","Fate","InvertedFate","ChromaticFate","Euphoria","InvertedEuphoria","ChromaticEuphoria"
}

while true do
    for _, v in pairs(game:GetDescendants()) do
        if v:IsA("Part") and table.find(allowedPartNames, v.Name) and v:FindFirstChild("ClickDetector") then
            fireclickdetector(v.ClickDetector)
        end
    end
    wait(0.8)
end
